fragment AttachmentParts on Attachment {
  __typename
  id
  fileName
  fileSize {
    bytes
    kiloBytes
    megaBytes
}
  fileExtension
  fileMimeType
  type
  createdAt {
    unixTimestamp
    iso8601
}
  createdBy {
  __typename
}
  updatedAt {
    unixTimestamp
    iso8601
}
  updatedBy {
  __typename
}
}
