fragment AttachmentUploadUrlParts on AttachmentUploadUrl {
  __typename
  attachment {
    id
    fileName
    fileExtension
    fileMimeType
    type
    createdBy {
  __typename
}
    updatedBy {
  __typename
}
}
  uploadFormUrl
  uploadFormData {
    key
    value
}
  expiresAt {
    unixTimestamp
    iso8601
}
}
