fragment AutoresponderParts on Autoresponder {
  __typename
  id
  name
  order
  messageSources
  conditions {
  __typename
}
  textContent
  markdownContent
  isEnabled
  responseDelaySeconds
  createdAt {
    unixTimestamp
    iso8601
}
  createdBy {
  __typename
}
  updatedAt {
    unixTimestamp
    iso8601
}
  updatedBy {
  __typename
}
}
