fragment BillingPlanParts on BillingPlan {
  __typename
  key
  name
  description
  features
  highlightedLabel
  isSelfCheckoutEligible
  monthlyPrice {
    amount
    currency
}
  yearlyPrice {
    amount
    currency
}
  prices {
    billingIntervalUnit
    billingIntervalCount
    currency
}
}
