fragment ChatAppSecretParts on ChatAppSecret {
  __typename
  chatAppId
  secret
  createdAt {
    unixTimestamp
    iso8601
}
  createdBy {
  __typename
}
  updatedAt {
    unixTimestamp
    iso8601
}
  updatedBy {
  __typename
}
}
