fragment ChatEntryParts on ChatEntry {
  __typename
  chatId
  text
  customerReadAt {
    unixTimestamp
    iso8601
}
  attachments {
    id
    fileName
    fileExtension
    fileMimeType
    type
    createdBy {
  __typename
}
    updatedBy {
  __typename
}
}
}
