fragment CompanyParts on Company {
  __typename
  id
  name
  domainName
  createdAt {
    unixTimestamp
    iso8601
}
  createdBy {
  __typename
}
  updatedAt {
    unixTimestamp
    iso8601
}
  updatedBy {
  __typename
}
  tier {
    id
    name
    externalId
    color
    isDefault
    defaultPriority
    defaultThreadPriority
    isMachineTier
    serviceLevelAgreements {
    id
    useBusinessHoursOnly
    threadPriorityFilter
    breachActions {
  __typename
}
    createdBy {
  __typename
}
    updatedBy {
  __typename
}
}
    createdAt {
    unixTimestamp
    iso8601
}
    createdBy {
  __typename
}
    updatedAt {
    unixTimestamp
    iso8601
}
    updatedBy {
  __typename
}
}
  threadChannelAssociations {
    id
    companyId
    createdAt {
    unixTimestamp
    iso8601
}
    createdBy {
  __typename
}
    updatedAt {
    unixTimestamp
    iso8601
}
    updatedBy {
  __typename
}
}
  contractValue
  accountOwner {
    id
    fullName
    publicName
    avatarUrl
    email
    roles {
    id
    name
    description
    permissions
    isAssignableToCustomer
    isAssignableToThread
    assignableBillingSeats
    requiresBillableSeat
    key
    customRoleId
}
    role {
    id
    name
    description
    permissions
    isAssignableToCustomer
    isAssignableToThread
    assignableBillingSeats
    requiresBillableSeat
    key
    customRoleId
}
    additionalLegacyRoles {
    id
    name
    description
    permissions
    isAssignableToCustomer
    isAssignableToThread
    assignableBillingSeats
    requiresBillableSeat
    key
    customRoleId
}
    slackIdentities {
    slackTeamId
    slackUserId
}
    labels {
    id
    createdBy {
  __typename
}
    updatedBy {
  __typename
}
}
    defaultSavedThreadsView {
    id
    name
    icon
    color
    isHidden
    createdBy {
  __typename
}
    updatedBy {
  __typename
}
}
    status
    statusChangedAt {
    unixTimestamp
    iso8601
}
    createdAt {
    unixTimestamp
    iso8601
}
    createdBy {
  __typename
}
    updatedAt {
    unixTimestamp
    iso8601
}
    updatedBy {
  __typename
}
    isDeleted
    deletedAt {
    unixTimestamp
    iso8601
}
    deletedBy {
  __typename
}
}
  isDeleted
  deletedAt {
    unixTimestamp
    iso8601
}
  deletedBy {
  __typename
}
}
