fragment ConnectedMSTeamsChannelParts on ConnectedMSTeamsChannel {
  __typename
  id
  workspaceId
  msTeamsTenantId
  msTeamsTeamId
  msTeamsChannelId
  name
  createdAt {
    unixTimestamp
    iso8601
}
  createdBy {
  __typename
}
  updatedAt {
    unixTimestamp
    iso8601
}
  updatedBy {
  __typename
}
  teamName
}
