fragment ConnectedDiscordChannelParts on ConnectedDiscordChannel {
  __typename
  id
  discordGuildId
  discordChannelId
  name
  isEnabled
  createdAt {
    unixTimestamp
    iso8601
}
  createdBy {
  __typename
}
  updatedAt {
    unixTimestamp
    iso8601
}
  updatedBy {
  __typename
}
}
