fragment CustomerGroupMembershipParts on CustomerGroupMembership {
  __typename
  customerId
  customerGroup {
    id
    name
    key
    color
    externalId
    createdBy {
  __typename
}
    updatedBy {
  __typename
}
}
  createdAt {
    unixTimestamp
    iso8601
}
  createdBy {
  __typename
}
  updatedAt {
    unixTimestamp
    iso8601
}
  updatedBy {
  __typename
}
}
