fragment CustomerCardInstanceErrorParts on CustomerCardInstanceError {
  __typename
  id
  customerId
  threadId
  customerCardConfig {
    id
    order
    title
    key
    defaultTimeToLiveSeconds
    apiUrl
    isEnabled
    createdBy {
  __typename
}
    updatedBy {
  __typename
}
}
  errorDetail {
  __typename
}
  createdAt {
    unixTimestamp
    iso8601
}
  createdBy {
  __typename
}
  updatedAt {
    unixTimestamp
    iso8601
}
  updatedBy {
  __typename
}
}
