fragment CustomerActorParts on CustomerActor {
  __typename
  customerId
  customer {
    id
    externalId
    fullName
    shortName
    avatarUrl
    isAnonymous
    createdBy {
  __typename
}
    updatedBy {
  __typename
}
    markedAsSpamBy {
  __typename
}
    identities {
  __typename
}
    status
}
}
