fragment DiscordMessageEntryParts on DiscordMessageEntry {
  __typename
  customerId
  discordMessageId
  markdownContent
  attachments {
    id
    fileName
    fileExtension
    fileMimeType
    type
    createdBy {
  __typename
}
    updatedBy {
  __typename
}
}
  lastEditedOnDiscordAt {
    unixTimestamp
    iso8601
}
  deletedOnDiscordAt {
    unixTimestamp
    iso8601
}
  discordMessageLink
}
