fragment EmailEntryParts on EmailEntry {
  __typename
  emailId
  to {
    name
    email
    emailActor {
  __typename
}
}
  from {
    name
    email
    emailActor {
  __typename
}
}
  additionalRecipients {
    name
    email
    emailActor {
  __typename
}
}
  hiddenRecipients {
    name
    email
    emailActor {
  __typename
}
}
  subject
  textContent
  hasMoreTextContent
  fullTextContent
  markdownContent
  hasMoreMarkdownContent
  fullMarkdownContent
  authenticity
  sentAt {
    unixTimestamp
    iso8601
}
  sendStatus
  receivedAt {
    unixTimestamp
    iso8601
}
  attachments {
    id
    fileName
    fileExtension
    fileMimeType
    type
    createdBy {
  __typename
}
    updatedBy {
  __typename
}
}
  isStartOfThread
  bounces {
    isSendRetriable
}
  category
}
