fragment EscalationPathParts on EscalationPath {
  __typename
  id
  name
  steps {
  __typename
}
  description
  createdAt {
    unixTimestamp
    iso8601
}
  createdBy {
  __typename
}
  updatedAt {
    unixTimestamp
    iso8601
}
  updatedBy {
  __typename
}
}
