fragment GenericThreadLinkParts on GenericThreadLink {
  __typename
  id
  title
  description
  url
  status
  threadId
  sourceId
  sourceType
  sourceStatus {
    key
    label
    color
    icon
}
  createdAt {
    unixTimestamp
    iso8601
}
  createdBy {
  __typename
}
  updatedAt {
    unixTimestamp
    iso8601
}
  updatedBy {
  __typename
}
}
