fragment GithubUserAuthIntegrationParts on GithubUserAuthIntegration {
  __typename
  id
  githubUsername
  createdAt {
    unixTimestamp
    iso8601
}
  createdBy {
  __typename
}
  updatedAt {
    unixTimestamp
    iso8601
}
  updatedBy {
  __typename
}
}
