fragment HelpCenterThemedImageParts on HelpCenterThemedImage {
  __typename
  light {
    id
    fileName
    fileExtension
    fileMimeType
    visibility
    createdBy {
  __typename
}
    updatedBy {
  __typename
}
}
  dark {
    id
    fileName
    fileExtension
    fileMimeType
    visibility
    createdBy {
  __typename
}
    updatedBy {
  __typename
}
}
}
