fragment HelpCenterPortalSettingsParts on HelpCenterPortalSettings {
  __typename
  isEnabled
  threadVisibility {
    customerCompany
    customerTenants
}
  formFields {
  __typename
}
  isAdditionalRecipientsEnabled
}
