fragment HelpCenterPortalSettingsDropdownFormFieldParts on HelpCenterPortalSettingsDropdownFormField {
  __typename
  id
  type
  label
  placeholder
  isRequired
  dropdownOptions {
    dropdownOptionId
    label
}
}
