fragment HelpCenterPortalSettingsTextFormFieldParts on HelpCenterPortalSettingsTextFormField {
  __typename
  id
  type
  label
  placeholder
  isRequired
  threadDetails {
    priority
    assignees {
  __typename
}
}
}
