fragment HelpCenterParts on HelpCenter {
  __typename
  id
  type
  publicName
  internalName
  description
  domainSettings {
    domainName
    customDomainName
}
  portalSettings {
    isEnabled
    formFields {
  __typename
}
    isAdditionalRecipientsEnabled
}
  headCustomJs
  bodyCustomJs
  isChatEnabled
  color
  socialPreviewImage {
    id
    fileName
    fileExtension
    fileMimeType
    visibility
    createdBy {
  __typename
}
    updatedBy {
  __typename
}
}
  access {
    tierIds
    tenantIds
    companyIds
    customerIds
}
  authMechanism {
  __typename
}
  publishedAt {
    unixTimestamp
    iso8601
}
  publishedBy {
  __typename
}
  isDeleted
  deletedAt {
    unixTimestamp
    iso8601
}
  deletedBy {
  __typename
}
  createdAt {
    unixTimestamp
    iso8601
}
  createdBy {
  __typename
}
  updatedAt {
    unixTimestamp
    iso8601
}
  updatedBy {
  __typename
}
}
