fragment HelpCenterDomainSettingsParts on HelpCenterDomainSettings {
  __typename
  domainName
  customDomainName
  customDomainNameVerificationTxtRecord {
    name
    value
}
  customDomainNameVerifiedAt {
    unixTimestamp
    iso8601
}
}
