fragment HelpCenterArticleParts on HelpCenterArticle {
  __typename
  id
  title
  description
  contentHtml
  slug
  status
  statusChangedAt {
    unixTimestamp
    iso8601
}
  statusChangedBy {
  __typename
}
  createdAt {
    unixTimestamp
    iso8601
}
  createdBy {
  __typename
}
  updatedAt {
    unixTimestamp
    iso8601
}
  updatedBy {
  __typename
}
  articleGroup {
    id
    name
    createdBy {
  __typename
}
    updatedBy {
  __typename
}
    slug
}
}
