fragment LabelTypeParts on LabelType {
  __typename
  id
  name
  icon
  color
  type
  description
  position
  externalId
  isArchived
  archivedBy {
  __typename
}
  archivedAt {
    unixTimestamp
    iso8601
}
  createdAt {
    unixTimestamp
    iso8601
}
  createdBy {
  __typename
}
  updatedAt {
    unixTimestamp
    iso8601
}
  updatedBy {
  __typename
}
}
