fragment LinearIssueThreadLinkParts on LinearIssueThreadLink {
  __typename
  id
  title
  description
  url
  status
  threadId
  sourceId
  sourceType
  createdAt {
    unixTimestamp
    iso8601
}
  createdBy {
  __typename
}
  updatedAt {
    unixTimestamp
    iso8601
}
  updatedBy {
  __typename
}
  linearIssueId
  linearIssueIdentifier
  linearIssueState {
    type
    label
    color
}
  linearIssueCreatedAt {
    unixTimestamp
    iso8601
}
  linearIssueUpdatedAt {
    unixTimestamp
    iso8601
}
  linearIssueUrl
}
