fragment QueryParts on Query {
  __typename
  myUserAccount {
    id
    fullName
    publicName
    email
}
  myUser {
    id
    fullName
    publicName
    avatarUrl
    email
    status
    createdBy {
  __typename
}
    updatedBy {
  __typename
}
    isDeleted
    deletedBy {
  __typename
}
}
  myMachineUser {
    id
    fullName
    publicName
    description
    type
    createdBy {
  __typename
}
    updatedBy {
  __typename
}
    isDeleted
    deletedBy {
  __typename
}
}
  myWorkspace {
    id
    name
    publicName
    isDemoWorkspace
    domainName
    domainNames
    createdBy {
  __typename
}
    updatedBy {
  __typename
}
}
  myPermissions {
    permissions
}
  mySlackIntegration {
    integrationId
    slackTeamName
    isReinstallRequired
    createdBy {
  __typename
}
    updatedBy {
  __typename
}
}
  myLinearIntegration {
    integrationId
    linearOrganisationName
    linearOrganisationId
    createdBy {
  __typename
}
    updatedBy {
  __typename
}
}
  myLinearIntegrationToken {
    token
}
  githubUserAuthIntegration {
    id
    githubUsername
    createdBy {
  __typename
}
    updatedBy {
  __typename
}
}
  workspaceCursorIntegration {
    id
    token
    createdBy {
  __typename
}
    updatedBy {
  __typename
}
}
  myJiraIntegrationToken {
    token
}
  myEmailSignature {
    text
    markdown
    createdBy {
  __typename
}
    updatedBy {
  __typename
}
}
  myBillingSubscription {
    status
    planKey
    planName
    interval
}
  myBillingRota {
    onRotaUserIds
    offRotaUserIds
}
  myPaymentMethod {
    isAvailable
}
  workspaceEmailSettings {
    isEnabled
    bccEmailAddresses
}
  workspaceChatSettings {
    isEnabled
}
  permissions {
    permissions
}
  workspaceMSTeamsIntegration {
    id
    msTeamsTenantId
    isReinstallRequired
    createdBy {
  __typename
}
    updatedBy {
  __typename
}
}
  myMSTeamsIntegration {
    id
    msTeamsTenantId
    isReinstallRequired
    msTeamsPreferredUsername
    createdBy {
  __typename
}
    updatedBy {
  __typename
}
}
  customerCardConfigs {
    id
    order
    title
    key
    defaultTimeToLiveSeconds
    apiUrl
    isEnabled
    createdBy {
  __typename
}
    updatedBy {
  __typename
}
}
  subscriptionEventTypes {
    eventType
    description
}
  businessHours {
    createdBy {
  __typename
}
    updatedBy {
  __typename
}
}
  businessHoursSlots {
    weekday
    opensAt
    closesAt
}
  workspaceHmac {
    hmacSecret
    createdBy {
  __typename
}
    updatedBy {
  __typename
}
}
}
