fragment RoleParts on Role {
  __typename
  id
  name
  description
  permissions
  isAssignableToCustomer
  isAssignableToThread
  assignableBillingSeats
  requiresBillableSeat
  key
  customRoleId
  scopeDefinitions {
    resource
}
}
