fragment SavedThreadsViewFilterTenantFieldParts on SavedThreadsViewFilterTenantField {
  __typename
  externalFieldId
  stringValue
  booleanValue
  numberValue
  stringArrayValue
  dateValue {
    unixTimestamp
    iso8601
}
}
