fragment SavedThreadsViewParts on SavedThreadsView {
  __typename
  id
  name
  icon
  color
  threadsFilter {
    statuses
    statusDetails
    priorities
    assignedToUser
    participants
    customerGroups
    companies
    tenants
    tiers
    labelTypeIds
    messageSource
    supportEmailAddresses
    slaTypes
    slaStatuses
    threadLinkGroupIds
    groupBy
    layout
}
  isHidden
  createdAt {
    unixTimestamp
    iso8601
}
  createdBy {
  __typename
}
  updatedAt {
    unixTimestamp
    iso8601
}
  updatedBy {
  __typename
}
}
