fragment ServiceLevelAgreementStatusTransitionedEntryParts on ServiceLevelAgreementStatusTransitionedEntry {
  __typename
  previousStatus
  nextStatus
  serviceLevelAgreement {
    id
    useBusinessHoursOnly
    threadPriorityFilter
    breachActions {
  __typename
}
    createdBy {
  __typename
}
    updatedBy {
  __typename
}
}
}
