fragment ServiceLevelAgreementParts on ServiceLevelAgreement {
  __typename
  id
  useBusinessHoursOnly
  threadPriorityFilter
  threadLabelTypeIdFilter {
    labelTypeIds
    requireAll
}
  breachActions {
  __typename
}
  createdAt {
    unixTimestamp
    iso8601
}
  createdBy {
  __typename
}
  updatedAt {
    unixTimestamp
    iso8601
}
  updatedBy {
  __typename
}
}
