fragment SlackMessageEntryParts on SlackMessageEntry {
  __typename
  slackMessageLink
  slackWebMessageLink
  text
  customerId
  relatedThread {
    threadId
}
  attachments {
    id
    fileName
    fileExtension
    fileMimeType
    type
    createdBy {
  __typename
}
    updatedBy {
  __typename
}
}
  lastEditedOnSlackAt {
    unixTimestamp
    iso8601
}
  deletedOnSlackAt {
    unixTimestamp
    iso8601
}
  reactions {
    name
    actors {
  __typename
}
    imageUrl
}
}
