fragment SnippetParts on Snippet {
  __typename
  id
  name
  text
  markdown
  path
  isDeleted
  createdAt {
    unixTimestamp
    iso8601
}
  createdBy {
  __typename
}
  updatedAt {
    unixTimestamp
    iso8601
}
  updatedBy {
  __typename
}
  deletedAt {
    unixTimestamp
    iso8601
}
  deletedBy {
  __typename
}
}
