fragment SurveyResponseParts on SurveyResponse {
  __typename
  id
  sentiment
  rating
  surveyId
  comment
  respondedAt {
    unixTimestamp
    iso8601
}
  createdAt {
    unixTimestamp
    iso8601
}
  createdBy {
  __typename
}
  updatedAt {
    unixTimestamp
    iso8601
}
  updatedBy {
  __typename
}
}
