fragment TenantFieldSchemaParts on TenantFieldSchema {
  __typename
  id
  source
  externalFieldId
  label
  type
  options
  isVisible
  order
  mapsTo
  createdAt {
    unixTimestamp
    iso8601
}
  createdBy {
  __typename
}
  updatedAt {
    unixTimestamp
    iso8601
}
  updatedBy {
  __typename
}
}
