fragment ThreadStatusDetailSnoozedParts on ThreadStatusDetailSnoozed {
  __typename
  snoozedAt {
    unixTimestamp
    iso8601
}
  snoozedUntil {
    unixTimestamp
    iso8601
}
  statusChangedAt {
    unixTimestamp
    iso8601
}
}
