fragment ThreadDiscussionResolvedEntryParts on ThreadDiscussionResolvedEntry {
  __typename
  customerId
  threadDiscussionId
  discussionType
  emailRecipients
  slackChannelName
  slackMessageLink
  resolvedAt {
    unixTimestamp
    iso8601
}
}
