fragment ThreadFieldSchemaParts on ThreadFieldSchema {
  __typename
  id
  label
  key
  description
  order
  type
  enumValues
  defaultStringValue
  defaultBooleanValue
  isRequired
  isAiAutoFillEnabled
  dependsOnThreadField {
    threadFieldSchemaId
    threadFieldSchemaValue
}
  dependsOnLabels {
    labelTypeId
}
  createdAt {
    unixTimestamp
    iso8601
}
  createdBy {
  __typename
}
  updatedAt {
    unixTimestamp
    iso8601
}
  updatedBy {
  __typename
}
}
