fragment ThreadStatusDetailLinearUpdatedParts on ThreadStatusDetailLinearUpdated {
  __typename
  statusChangedAt {
    unixTimestamp
    iso8601
}
  updatedAt {
    unixTimestamp
    iso8601
}
  linearIssueId
}
