fragment ThreadsDisplayOptionsParts on ThreadsDisplayOptions {
  __typename
  hasStatus
  hasCustomer
  hasCompany
  hasPreviewText
  hasTier
  hasCustomerGroups
  hasLabels
  hasLinearIssues
  hasJiraIssues
  hasLinkedThreads
  hasServiceLevelAgreements
  hasChannels
  hasLastUpdated
  hasAssignees
  hasRef
  hasIssueTrackerIssues
}
