fragment ThreadStatusDetailWaitingForDurationParts on ThreadStatusDetailWaitingForDuration {
  __typename
  statusChangedAt {
    unixTimestamp
    iso8601
}
  waitingUntil {
    unixTimestamp
    iso8601
}
}
