fragment ThreadLinkGroupSingleCompanyMetricsParts on ThreadLinkGroupSingleCompanyMetrics {
  __typename
  company {
    id
    name
    domainName
    createdBy {
  __typename
}
    updatedBy {
  __typename
}
    contractValue
    isDeleted
    deletedBy {
  __typename
}
}
  metrics {
    totalCount
}
}
