fragment ThreadDiscussionCursorWorkspaceBackgroundAgentChannelDetailsParts on ThreadDiscussionCursorWorkspaceBackgroundAgentChannelDetails {
  __typename
  cursorWorkspaceIntegrationId
  repositoryUrl
}
