fragment UserAuthDiscordChannelIntegrationConnectionParts on UserAuthDiscordChannelIntegrationConnection {
  __typename
  edges {
  ...UserAuthDiscordChannelIntegrationEdgeParts
}
  pageInfo {
  ...PageInfoParts
}
}
