fragment UserEmailActorParts on UserEmailActor {
  __typename
  userId
  user {
    id
    fullName
    publicName
    avatarUrl
    email
    status
    createdBy {
  __typename
}
    updatedBy {
  __typename
}
    isDeleted
    deletedBy {
  __typename
}
}
}
