fragment UserSlackIntegrationParts on UserSlackIntegration {
  __typename
  integrationId
  slackTeamName
  isReinstallRequired
  createdAt {
    unixTimestamp
    iso8601
}
  createdBy {
  __typename
}
  updatedAt {
    unixTimestamp
    iso8601
}
  updatedBy {
  __typename
}
}
