fragment UserAuthDiscordChannelIntegrationParts on UserAuthDiscordChannelIntegration {
  __typename
  id
  discordGuildId
  discordUserId
  discordUsername
  discordGlobalName
  discordUserEmail
  createdAt {
    unixTimestamp
    iso8601
}
  createdBy {
  __typename
}
  updatedAt {
    unixTimestamp
    iso8601
}
  updatedBy {
  __typename
}
}
