fragment WebhookTargetParts on WebhookTarget {
  __typename
  id
  url
  description
  eventSubscriptions {
    eventType
}
  version
  isEnabled
  createdAt {
    unixTimestamp
    iso8601
}
  createdBy {
  __typename
}
  updatedAt {
    unixTimestamp
    iso8601
}
  updatedBy {
  __typename
}
}
