fragment WorkspaceEmailSettingsParts on WorkspaceEmailSettings {
  __typename
  isEnabled
  workspaceEmailDomainSettings {
    domainName
    supportEmailAddress
    alternateSupportEmailAddresses
    isForwardingConfigured
    inboundForwardingEmail
    isDomainConfigured
}
  bccEmailAddresses
}
