fragment WorkspaceFileParts on WorkspaceFile {
  __typename
  id
  fileName
  fileSize {
    bytes
    kiloBytes
    megaBytes
}
  fileExtension
  fileMimeType
  visibility
  downloadUrl {
    downloadUrl
}
  createdAt {
    unixTimestamp
    iso8601
}
  createdBy {
  __typename
}
  updatedAt {
    unixTimestamp
    iso8601
}
  updatedBy {
  __typename
}
}
