fragment WorkspaceSlackChannelIntegrationConnectionParts on WorkspaceSlackChannelIntegrationConnection {
  __typename
  edges {
  ...WorkspaceSlackChannelIntegrationEdgeParts
}
  pageInfo {
  ...PageInfoParts
}
}
