fragment WorkspaceFileUploadUrlParts on WorkspaceFileUploadUrl {
  __typename
  workspaceFile {
    id
    fileName
    fileExtension
    fileMimeType
    visibility
    createdBy {
  __typename
}
    updatedBy {
  __typename
}
}
  uploadFormUrl
  uploadFormData {
    key
    value
}
  expiresAt {
    unixTimestamp
    iso8601
}
}
