fragment WorkspaceParts on Workspace {
  __typename
  id
  name
  publicName
  isDemoWorkspace
  domainName
  domainNames
  createdBy {
  __typename
}
  createdAt {
    unixTimestamp
    iso8601
}
  updatedBy {
  __typename
}
  updatedAt {
    unixTimestamp
    iso8601
}
  workspaceEmailSettings {
    isEnabled
    bccEmailAddresses
}
  workspaceChatSettings {
    isEnabled
}
  logo {
    id
    fileName
    fileExtension
    fileMimeType
    visibility
    createdBy {
  __typename
}
    updatedBy {
  __typename
}
}
}
