fragment WorkspaceDiscordChannelIntegrationConnectionParts on WorkspaceDiscordChannelIntegrationConnection {
  __typename
  edges {
  ...WorkspaceDiscordChannelIntegrationEdgeParts
}
  pageInfo {
  ...PageInfoParts
}
}
