fragment WorkspaceSlackIntegrationParts on WorkspaceSlackIntegration {
  __typename
  integrationId
  slackChannelName
  slackTeamId
  slackTeamName
  slackTeamImageUrl68px
  isReinstallRequired
  createdAt {
    unixTimestamp
    iso8601
}
  createdBy {
  __typename
}
  updatedAt {
    unixTimestamp
    iso8601
}
  updatedBy {
  __typename
}
}
