export const Doc = {
  CONNECTION_FIELDS: ["pageInfo", "nodes", "edges"],
  MUTATION_TYPES: [
    "update",
    "archive",
    "unarchive",
    "delete",
    "create",
    "upsert",
    "add",
    "remove",
    "set",
    "assign",
    "unassign",
    "change",
    "mark",
    "snooze",
    "reply",
    "send",
  ],
  SCALAR_STRING_NAMES: [],
  SCALAR_STRING_TYPE: "string",
  SCALAR_DATE_NAMES: ["DateTime"],
  SCALAR_DATE_TYPE: "Date",
  SCALAR_JSON_NAMES: ["JSON", "JsonObject"],
  SCALAR_JSON_TYPE: "Record<string, unknown>",
  SCALAR_DATE_OR_STRING_NAMES: [],
  SCALAR_DATE_OR_STRING_TYPE: "Date | string",
};
