query chatApps($first: Int, $after: String, $last: Int, $before: String) {
  chatApps(first: $first, after: $after, last: $last, before: $before) {
    ...ChatAppConnectionParts
  }
}

#import "chatAppConnectionParts.gql"
#import "chatAppEdgeParts.gql"
#import "chatAppParts.gql"
#import "workspaceFileParts.gql"
#import "fileSizeParts.gql"
#import "workspaceFileDownloadUrlParts.gql"
#import "dateTimeParts.gql"
#import "pageInfoParts.gql"
