query chatApp($chatAppId: ID!) {
  chatApp(chatAppId: $chatAppId) {
    ...ChatAppParts
  }
}

#import "chatAppParts.gql"
#import "workspaceFileParts.gql"
#import "fileSizeParts.gql"
#import "workspaceFileDownloadUrlParts.gql"
#import "dateTimeParts.gql"
