query companies($first: Int, $after: String, $last: Int, $before: String, $filters: CompaniesFilter) {
  companies(first: $first, after: $after, last: $last, before: $before, filters: $filters) {
    ...CompanyConnectionParts
  }
}

#import "companyConnectionParts.gql"
#import "companyEdgeParts.gql"
#import "companyParts.gql"
#import "dateTimeParts.gql"
#import "tierParts.gql"
#import "userParts.gql"
#import "roleParts.gql"
#import "roleScopeDefinitionParts.gql"
#import "roleScopeParts.gql"
#import "slackUserIdentityParts.gql"
#import "labelParts.gql"
#import "labelTypeParts.gql"
#import "savedThreadsViewParts.gql"
#import "savedThreadsViewFilterParts.gql"
#import "savedThreadsViewFilterThreadFieldParts.gql"
#import "savedThreadsViewFilterTenantFieldParts.gql"
#import "savedThreadsViewSortParts.gql"
#import "threadsDisplayOptionsParts.gql"
#import "pageInfoParts.gql"
