query connectedDiscordChannels($discordGuildId: String!, $first: Int, $after: String, $last: Int, $before: String) {
  connectedDiscordChannels(discordGuildId: $discordGuildId, first: $first, after: $after, last: $last, before: $before) {
    ...ConnectedDiscordChannelConnectionParts
  }
}

#import "connectedDiscordChannelConnectionParts.gql"
#import "pageInfoParts.gql"
#import "connectedDiscordChannelEdgeParts.gql"
#import "connectedDiscordChannelParts.gql"
#import "dateTimeParts.gql"
