query customRoles($first: Int, $after: String, $last: Int, $before: String) {
  customRoles(first: $first, after: $after, last: $last, before: $before) {
    ...CustomRoleConnectionParts
  }
}

#import "customRoleConnectionParts.gql"
#import "customRoleEdgeParts.gql"
#import "customRoleParts.gql"
#import "roleScopeDefinitionParts.gql"
#import "roleScopeParts.gql"
#import "dateTimeParts.gql"
#import "pageInfoParts.gql"
