query customerGroups($filters: CustomerGroupsFilter, $first: Int, $after: String, $last: Int, $before: String) {
  customerGroups(filters: $filters, first: $first, after: $after, last: $last, before: $before) {
    ...CustomerGroupConnectionParts
  }
}

#import "customerGroupConnectionParts.gql"
#import "customerGroupEdgeParts.gql"
#import "customerGroupParts.gql"
#import "dateTimeParts.gql"
#import "pageInfoParts.gql"
