query customRole($customRoleId: ID!) {
  customRole(customRoleId: $customRoleId) {
    ...CustomRoleParts
  }
}

#import "customRoleParts.gql"
#import "roleScopeDefinitionParts.gql"
#import "roleScopeParts.gql"
#import "dateTimeParts.gql"
