query customerCardConfigs {
  customerCardConfigs {
    ...CustomerCardConfigParts
  }
}

#import "customerCardConfigParts.gql"
#import "customerCardConfigApiHeaderParts.gql"
#import "dateTimeParts.gql"
