query escalationPaths($first: Int, $after: String, $last: Int, $before: String) {
  escalationPaths(first: $first, after: $after, last: $last, before: $before) {
    ...EscalationPathConnectionParts
  }
}

#import "escalationPathConnectionParts.gql"
#import "escalationPathEdgeParts.gql"
#import "escalationPathParts.gql"
#import "dateTimeParts.gql"
#import "pageInfoParts.gql"
