query helpCenters($first: Int, $after: String, $last: Int, $before: String) {
  helpCenters(first: $first, after: $after, last: $last, before: $before) {
    ...HelpCenterConnectionParts
  }
}

#import "helpCenterConnectionParts.gql"
#import "helpCenterEdgeParts.gql"
#import "helpCenterParts.gql"
#import "helpCenterDomainSettingsParts.gql"
#import "helpCenterDomainNameVerificationTxtRecordParts.gql"
#import "dateTimeParts.gql"
#import "helpCenterPortalSettingsParts.gql"
#import "helpCenterPortalSettingsThreadVisibilityParts.gql"
#import "helpCenterThemedImageParts.gql"
#import "workspaceFileParts.gql"
#import "fileSizeParts.gql"
#import "workspaceFileDownloadUrlParts.gql"
#import "helpCenterAccessSettingsParts.gql"
#import "pageInfoParts.gql"
