query labelTypes($filters: LabelTypeFilter, $first: Int, $after: String, $last: Int, $before: String) {
  labelTypes(filters: $filters, first: $first, after: $after, last: $last, before: $before) {
    ...LabelTypeConnectionParts
  }
}

#import "labelTypeConnectionParts.gql"
#import "labelTypeEdgeParts.gql"
#import "labelTypeParts.gql"
#import "dateTimeParts.gql"
#import "pageInfoParts.gql"
