query machineUsers($filters: MachineUsersFilter, $first: Int, $after: String, $last: Int, $before: String) {
  machineUsers(filters: $filters, first: $first, after: $after, last: $last, before: $before) {
    ...MachineUserConnectionParts
  }
}

#import "machineUserConnectionParts.gql"
#import "machineUserEdgeParts.gql"
#import "machineUserParts.gql"
#import "workspaceFileParts.gql"
#import "fileSizeParts.gql"
#import "workspaceFileDownloadUrlParts.gql"
#import "dateTimeParts.gql"
#import "pageInfoParts.gql"
