query myFavoritePages($first: Int, $after: String, $last: Int, $before: String) {
  myFavoritePages(first: $first, after: $after, last: $last, before: $before) {
    ...FavoritePageConnectionParts
  }
}

#import "favoritePageConnectionParts.gql"
#import "pageInfoParts.gql"
#import "favoritePageEdgeParts.gql"
#import "favoritePageParts.gql"
#import "dateTimeParts.gql"
