query myLinearInstallationInfo($redirectUrl: String!) {
  myLinearInstallationInfo(redirectUrl: $redirectUrl) {
    ...UserLinearInstallationInfoParts
  }
}

#import "userLinearInstallationInfoParts.gql"
