query myMSTeamsInstallationInfo($redirectUrl: String!) {
  myMSTeamsInstallationInfo(redirectUrl: $redirectUrl) {
    ...UserMSTeamsInstallationInfoParts
  }
}

#import "userMSTeamsInstallationInfoParts.gql"
