query mySlackInstallationInfo($redirectUrl: String!) {
  mySlackInstallationInfo(redirectUrl: $redirectUrl) {
    ...UserSlackInstallationInfoParts
  }
}

#import "userSlackInstallationInfoParts.gql"
