query myWorkspaces($first: Int, $after: String, $last: Int, $before: String) {
  myWorkspaces(first: $first, after: $after, last: $last, before: $before) {
    ...WorkspaceConnectionParts
  }
}

#import "workspaceConnectionParts.gql"
#import "workspaceEdgeParts.gql"
#import "workspaceParts.gql"
#import "dateTimeParts.gql"
#import "workspaceEmailSettingsParts.gql"
#import "workspaceEmailDomainSettingsParts.gql"
#import "dnsRecordParts.gql"
#import "workspaceChatSettingsParts.gql"
#import "workspaceFileParts.gql"
#import "fileSizeParts.gql"
#import "workspaceFileDownloadUrlParts.gql"
#import "pageInfoParts.gql"
