query savedThreadsViews($first: Int, $after: String, $last: Int, $before: String) {
  savedThreadsViews(first: $first, after: $after, last: $last, before: $before) {
    ...SavedThreadsViewConnectionParts
  }
}

#import "savedThreadsViewConnectionParts.gql"
#import "pageInfoParts.gql"
#import "savedThreadsViewEdgeParts.gql"
#import "savedThreadsViewParts.gql"
#import "savedThreadsViewFilterParts.gql"
#import "savedThreadsViewFilterThreadFieldParts.gql"
#import "savedThreadsViewFilterTenantFieldParts.gql"
#import "dateTimeParts.gql"
#import "savedThreadsViewSortParts.gql"
#import "threadsDisplayOptionsParts.gql"
