query searchCompanies($searchQuery: CompaniesSearchQuery!, $filters: CompaniesFilter, $first: Int, $after: String, $last: Int, $before: String) {
  searchCompanies(searchQuery: $searchQuery, filters: $filters, first: $first, after: $after, last: $last, before: $before) {
    ...CompanySearchResultConnectionParts
  }
}

#import "companySearchResultConnectionParts.gql"
#import "companySearchResultEdgeParts.gql"
#import "companySearchResultParts.gql"
#import "companyParts.gql"
#import "dateTimeParts.gql"
#import "tierParts.gql"
#import "userParts.gql"
#import "roleParts.gql"
#import "roleScopeDefinitionParts.gql"
#import "roleScopeParts.gql"
#import "slackUserIdentityParts.gql"
#import "labelParts.gql"
#import "labelTypeParts.gql"
#import "savedThreadsViewParts.gql"
#import "savedThreadsViewFilterParts.gql"
#import "savedThreadsViewFilterThreadFieldParts.gql"
#import "savedThreadsViewFilterTenantFieldParts.gql"
#import "savedThreadsViewSortParts.gql"
#import "threadsDisplayOptionsParts.gql"
#import "pageInfoParts.gql"
