query searchSlackUsers($slackTeamId: String!, $slackChannelId: String!, $searchQuery: String!, $first: Int, $after: String, $last: Int, $before: String) {
  searchSlackUsers(slackTeamId: $slackTeamId, slackChannelId: $slackChannelId, searchQuery: $searchQuery, first: $first, after: $after, last: $last, before: $before) {
    ...SlackUserConnectionParts
  }
}

#import "slackUserConnectionParts.gql"
#import "slackUserEdgeParts.gql"
#import "slackUserParts.gql"
#import "dateTimeParts.gql"
#import "pageInfoParts.gql"
