query serviceAuthorization($serviceAuthorizationId: ID!) {
  serviceAuthorization(serviceAuthorizationId: $serviceAuthorizationId) {
    ...ServiceAuthorizationParts
  }
}

#import "serviceAuthorizationParts.gql"
#import "dateTimeParts.gql"
