query threadFieldSchemas($first: Int, $after: String, $last: Int, $before: String) {
  threadFieldSchemas(first: $first, after: $after, last: $last, before: $before) {
    ...ThreadFieldSchemaConnectionParts
  }
}

#import "threadFieldSchemaConnectionParts.gql"
#import "threadFieldSchemaEdgeParts.gql"
#import "threadFieldSchemaParts.gql"
#import "dependsOnThreadFieldTypeParts.gql"
#import "dependsOnLabelTypeParts.gql"
#import "dateTimeParts.gql"
#import "pageInfoParts.gql"
