query threadClustersPaginated($first: Int, $after: String, $last: Int, $before: String, $filters: ThreadClustersFilter) {
  threadClustersPaginated(first: $first, after: $after, last: $last, before: $before, filters: $filters) {
    ...ThreadClusterConnectionParts
  }
}

#import "threadClusterConnectionParts.gql"
#import "threadClusterEdgeParts.gql"
#import "threadClusterParts.gql"
#import "dateTimeParts.gql"
#import "minimalThreadWithDistanceParts.gql"
#import "pageInfoParts.gql"
