query tiers($first: Int, $after: String, $last: Int, $before: String) {
  tiers(first: $first, after: $after, last: $last, before: $before) {
    ...TierConnectionParts
  }
}

#import "tierConnectionParts.gql"
#import "tierEdgeParts.gql"
#import "tierParts.gql"
#import "dateTimeParts.gql"
#import "pageInfoParts.gql"
