query userAuthSlackIntegrationByThreadId($threadId: ID!) {
  userAuthSlackIntegrationByThreadId(threadId: $threadId) {
    ...UserAuthSlackIntegrationParts
  }
}

#import "userAuthSlackIntegrationParts.gql"
#import "dateTimeParts.gql"
