query userSlackChannelMemberships($slackTeamId: String!) {
  userSlackChannelMemberships(slackTeamId: $slackTeamId) {
    ...SlackChannelMembershipParts
  }
}

#import "slackChannelMembershipParts.gql"
