query userAuthDiscordChannelInstallationInfo($redirectUrl: String!) {
  userAuthDiscordChannelInstallationInfo(redirectUrl: $redirectUrl) {
    ...UserAuthDiscordChannelInstallationInfoParts
  }
}

#import "userAuthDiscordChannelInstallationInfoParts.gql"
