query userAuthSlackIntegration($slackTeamId: String!) {
  userAuthSlackIntegration(slackTeamId: $slackTeamId) {
    ...UserAuthSlackIntegrationParts
  }
}

#import "userAuthSlackIntegrationParts.gql"
#import "dateTimeParts.gql"
