query webhookTarget($webhookTargetId: ID!) {
  webhookTarget(webhookTargetId: $webhookTargetId) {
    ...WebhookTargetParts
  }
}

#import "webhookTargetParts.gql"
#import "webhookTargetEventSubscriptionParts.gql"
#import "dateTimeParts.gql"
