query webhookTargets($first: Int, $after: String, $last: Int, $before: String) {
  webhookTargets(first: $first, after: $after, last: $last, before: $before) {
    ...WebhookTargetConnectionParts
  }
}

#import "webhookTargetConnectionParts.gql"
#import "webhookTargetEdgeParts.gql"
#import "webhookTargetParts.gql"
#import "webhookTargetEventSubscriptionParts.gql"
#import "dateTimeParts.gql"
#import "pageInfoParts.gql"
