query workspaceDiscordIntegration($integrationId: ID!) {
  workspaceDiscordIntegration(integrationId: $integrationId) {
    ...WorkspaceDiscordIntegrationParts
  }
}

#import "workspaceDiscordIntegrationParts.gql"
#import "dateTimeParts.gql"
