query workspace($workspaceId: ID!) {
  workspace(workspaceId: $workspaceId) {
    ...WorkspaceParts
  }
}

#import "workspaceParts.gql"
#import "dateTimeParts.gql"
#import "workspaceEmailSettingsParts.gql"
#import "workspaceEmailDomainSettingsParts.gql"
#import "dnsRecordParts.gql"
#import "workspaceChatSettingsParts.gql"
#import "workspaceFileParts.gql"
#import "fileSizeParts.gql"
#import "workspaceFileDownloadUrlParts.gql"
