query workspaceSlackIntegrations($first: Int, $after: String, $last: Int, $before: String) {
  workspaceSlackIntegrations(first: $first, after: $after, last: $last, before: $before) {
    ...WorkspaceSlackIntegrationConnectionParts
  }
}

#import "workspaceSlackIntegrationConnectionParts.gql"
#import "workspaceSlackIntegrationEdgeParts.gql"
#import "workspaceSlackIntegrationParts.gql"
#import "dateTimeParts.gql"
#import "pageInfoParts.gql"
