query workspaceSlackInstallationInfo($redirectUrl: String!) {
  workspaceSlackInstallationInfo(redirectUrl: $redirectUrl) {
    ...WorkspaceSlackInstallationInfoParts
  }
}

#import "workspaceSlackInstallationInfoParts.gql"
