query workspaceSlackChannelInstallationInfo($redirectUrl: String!) {
  workspaceSlackChannelInstallationInfo(redirectUrl: $redirectUrl) {
    ...WorkspaceSlackChannelInstallationInfoParts
  }
}

#import "workspaceSlackChannelInstallationInfoParts.gql"
