query workspaceDiscordChannelInstallationInfo($redirectUrl: String!) {
  workspaceDiscordChannelInstallationInfo(redirectUrl: $redirectUrl) {
    ...WorkspaceDiscordChannelInstallationInfoParts
  }
}

#import "workspaceDiscordChannelInstallationInfoParts.gql"
