query workspaceMSTeamsInstallationInfo($redirectUrl: String!) {
  workspaceMSTeamsInstallationInfo(redirectUrl: $redirectUrl) {
    ...WorkspaceMSTeamsInstallationInfoParts
  }
}

#import "workspaceMSTeamsInstallationInfoParts.gql"
