query workspaceDiscordIntegrations($first: Int, $after: String, $last: Int, $before: String) {
  workspaceDiscordIntegrations(first: $first, after: $after, last: $last, before: $before) {
    ...WorkspaceDiscordIntegrationConnectionParts
  }
}

#import "workspaceDiscordIntegrationConnectionParts.gql"
#import "workspaceDiscordIntegrationEdgeParts.gql"
#import "workspaceDiscordIntegrationParts.gql"
#import "dateTimeParts.gql"
#import "pageInfoParts.gql"
